<?php

//Core
$l[1]['banner'] = '/dining/template/headers/core.png';
$l[1]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=17&locationName=Core+163130&naFlag=1';

//BK
$l[2]['banner'] = '/dining/template/headers/burger_king.png';

//Cactus
$l[5]['banner'] = '/dining/template/headers/cactus.png';
$l[5]['nutrition'] ='http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=21&locationName=Cactus+Grill&naFlag=1';


//pangea
$l[20]['banner'] = '/dining/template/headers/pangea.png';
$l[20]['nutrition'] ='http://muley.sunion.arizona.edu/foodpro/menuSamp.asp?locationNum=55&locationName=Three+Cheeses+&sName=The+University+of+Arizona+Student+Union&naFlag=1';

//sonora
$l[21]['banner'] = '/dining/template/headers/sabor.png';

//canyon
$l[22]['banner'] = '/dining/template/headers/canyon.png';
$l[22]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=67&locationName=Canyon+Cafe&naFlag=1';

//cellar
$l[23]['banner'] = '/dining/template/headers/cellar.png';
$l[23]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=72&locationName=The+Cellar&naFlag=1';

//Chick-fil-a
$l[24]['banner'] = '/dining/template/headers/chik-fil-a.png';

//papa johns
$l[26]['banner'] = '/dining/template/headers/papa_johns.png';

//IQ Fresh
$l[27]['banner'] = '/dining/template/headers/iq.png';
$l[27]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=16&locationName=IQ+Fresh&naFlag=1';

//on deck
$l[28]['banner'] = '/dining/template/headers/On_Deck_Deli.png';
$l[28]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=41&locationName=On+Deck+Deli+&naFlag=1';

//panda express
$l[29]['banner'] = '/dining/template/headers/panda_express.png';

//Redington Restaurant
$l[30]['banner'] = '/dining/template/headers/redington.png';
$l[30]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=25&locationName=Redington+Room+&naFlag=1';
$l[30]['ad'] = '<a href="http://www.youtube.com/embed/G_OPQ1JMX0U?autoplay=1" rel="shadowbox;width=560;height=347;"><img src="/dining/template/images/Redington_video_still.jpg" /></a>';

//U Mart
$l[31]['banner'] = '/dining/template/headers/U-Mart.png';
$l[31]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=98&locationName=U+Mart&naFlag=1';

//starbucks @ the Bookstore
$l[32]['banner'] = '/template/images/banners/starbucksWB3_SU.jpg';

//starbucks @ the Library
$l[45]['banner'] = '/template/images/banners/starbucksWB1_ML.jpg';

//bageltalk
$l[35]['banner'] = '/dining/template/headers/Bagel_Talk.png';
// $l[35]['ad'] = '<a href="/dining/template/movies/BagelTalk.mov" rel="shadowbox;width=600;height=355;"><img src="/dining/template/images/video_placeholder.jpg" /></a>';

//papa johns park
$l[36]['banner'] = '/dining/template/headers/papa_johns.png';

//Park Avenue Market
$l[37]['banner'] = '/dining/template/headers/park_market.png';
$l[37]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=19&locationName=Park+Student+Union&naFlag=1';

//core park
$l[38]['banner'] = '/dining/template/headers/core.png';

//Bookend Cafe
$l[40]['banner'] = '/dining/template/headers/Bookend_Cafe.png';
$l[40]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=61&locationName=Bookend+Cafe&naFlag=1';

//The Counter
$l[41]['banner'] = '/template/images/banners/14_The Counter_Web_Banner.png'; 
$l[41]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=36&locationName=Eller+Deli&naFlag=1';

//Highland
$l[42]['banner'] = '/dining/template/headers/Highland_Market.png';
$l[42]['nutrition'] = 'http://muley.sunion.arizona.edu/foodpro/nutframe.asp?sName=The+University+of+Arizona+Student+Union&locationNum=90&locationName=Highland+Marketplace&naFlag=1';

//boost
$l[57]['banner'] = '/dining/template/headers/Boost.png';

//fro yo
$l[60]['banner'] = '/dining/template/headers/froyo.png';

//fuel
$l[61]['banner'] = '/dining/template/headers/fuel.png';
$l[61]['ad'] = '<a href="http://www.youtube.com/embed/PR_pTeTZql0?autoplay=1" rel="shadowbox;width=560;height=347;"><img src="/dining/template/images/Fuel_video_still.jpg" /></a>';

//La Petite Patiiserie
$l[62]['banner'] = '/dining/template/headers/lapetite.png';

//The Mesa Room
$l[63]['banner'] = '/dining/template/headers/mesa.png';

//pinkberry
$l[66]['banner'] = '/dining/template/headers/pinkberry.png';

//einsteins
$l[67]['banner'] = '/dining/template/headers/einsteins.jpg';

// bear down kitchen
$l[68]['banner'] = '/dining/template/headers/BDK_Web_banner.jpg';
// Slot canyon
$l[80]['banner'] = '/dining/template/headers/slotcanyon.jpg';