<?php

	require($_SERVER['DOCUMENT_ROOT'].'/template/'.'global.inc');
  $page_options['title'] = 'Privacy Statement';
  page_start($page_options);
?>
<h2>Arizona Student Unions Electronic Privacy Statement</h2>
<p>(Adapted from the <a href="http://w3.arizona.edu/~security/uaelectprivstmt.htm">University of Arizona Electronic Privacy Statement</a>)</p>
<p>The Arizona Student Unions (Student Unions) provides online information and services to students, employees and the public to supplement services provided on campus. This privacy statement provides information required by Arizona law about privacy, confidentiality and related policies for individuals who use our official websites and other electronic services. This statement applies to all electronic information collected by or submitted to the Student Unions. It is not meant to be construed as a contractual promise. Additional UA Policies which provide information about the use of computing and communications systems at UA can be found at <a href="http://w3.arizona.edu/~security/pandp.htm">http://w3.arizona.edu/~security/pandp.htm</a>.</p>
<p>Student Unions websites may contain links to external websites. However, the Student Unions does not endorse or take any responsibility for the privacy practices or policies of any site not sponsored by the Student Unions.</p>
<h2>INFORMATION COLLECTED BY THE STUDENT UNIONS</h2>
<p><b>E-mail and Form Information.</b> The Student Unions do not obtain personal information about you when you visit our websites or through other online services unless you provide us that information voluntarily. If an individual sends an e-mail message with a question or comment or fills out a web-based form, and either form or communication contains personal information, that information will only be used to directly respond to the requestor, unless otherwise stated specifically. The request for information may be redirected to another part of the University that may be in a better position to respond to the request. Any personal information you provide will not be released to outside parties unless legally required to do so in connection with legal proceedings or law enforcement investigations.</p>
<p><b>System-Generated Information.</b> In addition to information actively provided by individuals using Student Unions websites and other online services, the Student Unions may record information such as the following each time the Student Unions services are used:</p>
<p>&#149; Internet address of the computer being used<br>
	&#149; Web pages requested<br>
	&#149; Network software access<br>
	&#149; Referring web page<br>
	&#149; Browser used<br>
	&#149; Date, time and duration of activity<br>
	&#149; Passwords and accounts accessed<br>
	&#149; Volume of data storage and transfers</p>
<p>The Student Unions uses this information to monitor, preserve and enhance the functioning and integrity of the system. Information is collected for analysis and statistical purposes, and is used to help diagnose problems with the server and to carry out other administrative tasks, such as assessing what information is of most interest, determining technical design specifications and identifying system performance and/or problem areas. This information is not used in any way that would reveal personal information to external constituencies unless legally required to do so in connection with legal proceedings or law enforcement investigations.</p>
<p><b>Monitoring.</b> In cases of suspected violations of UA policies, especially unauthorized access to computing systems, the system administrator concerned may authorize detailed session logging. This may involve capturing and retaining a complete keystroke log of an entire session. In addition, a system administrator for the equipment involved may authorize limited searching of user files on individual or networked computers to gather evidence on a suspected violation.</p>
<p><b>Cookies.</b> Cookies are short pieces of information used by web browsers to remember information provided by the user, such as passwords and preferences from past visits. Additional information on cookies is available at <a href="http://www.cookiecentral.com/">Cookie Central</a> <a href="http://cookiecentral.com/"></a>and in this Information Bulletin, <a href="http://ciac.llnl.gov/ciac/bulletins/i-034.shtml">I-034: Internet Cookies</a>, from the Department of Energy Computer Incident Advisory Center. Some Student Unions websites use cookies to store service information. Some web-based services require cookies for access. Any information that the Student Unions may store in cookies is used exclusively for internal purposes only and will not disclose personal information to outside parties unless legally required to do so in connection with legal proceedings or law enforcement investigations.</p>
<h2>ALTERNATIVES TO ELECTRONIC TRANSACTIONS</h2>
<p>The Student Unions provide online access to information and services for students, employees and members of the public. If you prefer not to provide any information to the university online, you may cancel the transaction and contact the administrative unit responsible for the service to learn about available options for conducting business in person, by mail or by telephone.</p>
<h2>DISCLOSURE OF INFORMATION </h2>
<p>The Student Unions do not sell or distribute confidential information it collects online to individuals or entities not affiliated with the university, except in the very limited circumstances described below. Non-confidential information may be sold or distributed pursuant to Arizona Public Records law.</p>
<p>University and Arizona Board of Regents policies protect the confidentiality of student educational records and employee personnel information. These policies explain what information may be shared with the public or anyone who requests it. They also explain what information is protected as confidential; confidential information will not be disclosed without the consent of the student or employee, except under subpoena or court order or in case of an emergency.</p>
<p><b>Student records.</b> Student records are protected by the federal Family Education Rights and Privacy Act (FERPA), Arizona law, and university policy. Information about student access to education records and protection of education records is available at: <a href="http://w3.arizona.edu/~policy/ferpa.shtml">http://w3.arizona.edu/~policy/ferpa.shtml</a>. That policy also provides information on a student's right to limit access to otherwise public directory information.</p>
<p><b>Chat rooms, forums, message boards, and news groups. </b>UA does not routinely retain logs or copies of chat rooms, forums, message boards or news groups available to its users. However, information disclosed in these areas is public. Academic chat rooms and discussions conducted in connection with UA classes may be logged and will be treated as confidential educational records under FERPA if personal information is logged.</p>
<p><b>Employee records.</b> Employee records are protected by Arizona Board of Regents policy <a href="http://w3.arizona.edu/~security/ABOR-policy.pdf">6-912</a> and by Arizona law.</p>
<b></b><p><b>Public records law.</b> Under the Arizona Public Records Law, UA may be required to provide information in university records to a third party. Commercial users may purchase public record information, such as non-confidential lists of students and employees. Confidential information protected by FERPA or by other laws or Board policy will not be disclosed in response to a public records request.</p>
<p><b>Contractors. </b>From time to time, individuals or companies under contract with the university may have access to confidential information in the course of the service they provide to the university, but those entities are not permitted to use or re-disclose that information for unauthorized purposes. No other entities are authorized to collect information through UA's sites.</p>
<h2>SECURITY<b> </b></h2>
<p>Although every effort is made to secure network communications, the Student Unions cannot ensure the privacy of online communications. Individuals using online services should also take steps to protect personal information, such as closing the web browser when finished using the site. Failure to do so may result in personal information being viewed by someone else using the same computer.</p>
<p>The Student Unions accept credit card payments online for a variety of goods and services. Unless otherwise noted on the site, all university credit card transactions are encrypted. Confidential information entered to complete a transaction will not be used by the Student Unions for any other purpose unless the purpose is described on the site.</p>
<p>University-owned computers and equipment may be examined by authorized individuals to detect illegal software and to evaluate the security of the network.</p>
<p>Additional information is available on the Information Security and Privacy web site located at: <a href="http://w3.arizona.edu/~security">http://w3.arizona.edu/~security</a>. If you have additional questions about online privacy or security, you can contact the Business Continuity and Information Security (BCIS) office, via e-mail to <a href="mailto:bcis@u.arizona.edu">bcis@u.arizona.edu</a>, by phone (520) 621-4482, or you can send an inquiry by mail to Business Continuity and Information Security, 1077 N. Highland Ave., Tucson, AZ 85721.</p>
<p>If you have specific questions about privacy policies with regards to the Arizona Student Unions websites, please contact the Arizona Student Unions administration office or send email to <a href="mailto:web@union.arizona.edu">web@union.arizona.edu</a>.</p>
<?php page_finish() ?>