<?php

/* variables that set the characteristics of how
   the current section should be displayed */
   

$area = 'csil';
$template = 'standard';


/* the main page for this section */
$section_title 		= 'clubs & organizations';
$section_title_img	= '/csil/clubs/clubs.gif';
$section_url 		= '/csil/clubs/index.php';

$photo_url		= '/csil/clubs/ASUAwebAvatar.jpg';
$photo_alt		= 'ASUA';	


/* links to show for the parents */
/* lower indexes are more ancestral */
$parent_title	= array('involvement');
$parent_url		= array('/csil/index.php');


/* links for the section's children */

$child_title = 	array('Corporate Sponsorships',
					  /*'Club Listings',
					  'Student Organization Handbook',
					  'How Do I?',
					  'Student Organization Resources',
					  'Advisor Resources',
					  'Funding Options',
					  'Common Forms',
					  'Banner Hanging Policy',
					  'ASUA Club Affairs',
					  'Graduate & Student Professional Council',
					  'Hazing on Campus'*/
					  
					  );
					         
 $child_url = 	array('CorpSpons',
 					  /*'http://secureapp.netclubmgr.com/ICS/CM/V2/Student/Index.aspx?uid=azuniv',  
					  '/csil/clubs/handbook.php',
					  '/csil/clubs/howto.php',
					  '/csil/clubs/leadership/index.php',
					  '/csil/clubs/advisors/index.php',
					  '/csil/clubs/funding.php',
					  '/csil/clubs/forms.php',
					  '/rooms/banners.php',
					  'http://www.asua.arizona.edu',
					  'http://www.gpsc.arizona.edu',
					  '/csil/haze/index.php'*/
					
					  );

?>