<div id="logo">
  <img src="/cheapeats/images/3.gif"/>
</div>
<div id="desc">
    <p>$3 Combo Meals &middot; Every Wednesday &middot; January 19-May 4 &middot; 10:30a-1:30p</p>
</div>
<style>
.color-row{
  background-color:#E5E4DE;
}
td{
  padding:3px;
}
</style>
<table style="clear:both; font-size:10px; padding-top:15px;" cellspacing="0" cellpadding="0">
  <tr class="color-row">
    <td style="width:175px;">3 Cheeses &amp; a Noodle (SUMC)</td>
    <td>Choice of any Pasta with Garlic Bread, Side Salad &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td>Bagel Talk (PSU) </td>
    <td>Bagel Sandwich, Chips &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td>Bookend Café</td>
    <td>Bagel Sandwich &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td>Cactus Grill (SUMC)</td>
    <td>Savvy Student Hotline Entr&eacute;e with 2 Sides &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td>Cafe Sonora (SUMC)</td>
    <td>2 Queso Fresca Enchiladas with Rice &amp; Beans &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td>Chick-fil-a (SUMC)</td>
    <td>CFA Sandwich, Waffles Fries &amp; Drink</td>
  </tr>
  <tr class="color-row">
    <td>The Cellar (SUMC)</td>
    <td>Grilled Chicken Sandwich with One Side &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td>Core (SUMC)</td>
    <td>Core Salad &amp; Bottled Water</td>
  </tr>
  <tr class="color-row">
    <td>Core (PSU)</td>
    <td>Core Salad &amp; 16 oz Drink</td>
  </tr>
  <tr>
    <td>Eller Deli (McClelland Hall)</td>
    <td>Deli Sandwich, Salad &amp; Bottled Water</td>
  </tr>
  <tr class="color-row">
    <td>Highland Market (6th &amp; Highland)</td>
    <td>Cheeseburger, Small Fries &amp; 24 oz Drink</td>
  </tr>
  <tr >
    <td>IQ Fresh (SUMC)</td>
    <td>Grilled Chicken Ceasar Wrap &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td>McKale Food Stop (McKale Bldg)</td>
    <td>Two Hot Dogs, Chips, 24 oz Fountain Soda</td>
  </tr>
  <tr>
    <td>On Deck Deli (SUMC)</td>
    <td>Bagel Sandwich, One Side &amp; 24 oz Drink</td>
  </tr>
   <tr class="color-row">
    <td>Park Ave. Market Food Court (PSU)</td>
    <td>Savvy Student Hotline Entr&eacute;e with 2 Sides &amp; 24 oz Drink</td>
  </tr>
</table>