<div id="logo">
  <img src="/cheapeats/images/4.gif"/>
</div>
<div id="desc">
    <p>$4 Combo Meals &middot; Monday-Thursday &middot; 4:30p-Close</p>
</div>
<style>
.color-row{
  background-color:#E5E4DE;
}
td{
  padding:3px;
}
</style>
<table style="clear:both; font-size:10px; padding-top:15px;" cellspacing="0" cellpadding="0">
   <tr class="color-row">
    <td  style="width:175px;">Cafe Sonora (SUMC)</td>
    <td>Ground Beef Taco, Bean Tostada, Mexican Rice &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td>3 Cheeses &amp; a Noodle (SUMC)</td>
    <td>Baked Ziti, Caesar Salad, Garlic Bread &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td colspan="2">*Hang on to those piggy banks...there's more to come!</td>
  </tr>
</table>




