<div id="logo">
  <img src="/cheapeats/images/5.gif"/>
</div>
<div id="desc">
    <p>$5 Combo Meals &middot; Every Friday &middot; All Day</p>
</div>
<style>
.color-row{
  background-color:#E5E4DE;
}
td{
  padding:3px;
}
</style>
<table style="clear:both; font-size:10px; padding-top:15px;" cellspacing="0" cellpadding="0">
  <tr class="color-row">
    <td style="width:175px;">3 Cheeses &amp; a Noodle (SUMC)</td>
    <td>Veggie or Meat Lasagna with Salad, Garlic Bread &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td style="width:175px;">Cactus Grill (SUMC)</td>
    <td>3-Strip Chicken Basket &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td style="width:175px;">Café Sonora (SUMC)</td>
    <td>Beef, Chicken or Bean Chimichangas with Rice, Refried Beans, or Black Beans &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td style="width:175px;">IQ Fresh (SUMC)</td>
    <td>Turkey, Ham, or Roast Beef Wrap with Small Fries &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td style="width:175px;">Nugent Hot Dog Cart (Nugent Bldg)</td>
    <td>Two Chili Dogs and a 12oz Can of Soda</td>
  </tr>
  <tr>
    <td style="width:175px;">On Deck Deli (SUMC)</td>
    <td>Bagel Sandwich with Pasta or Potato Salad &amp; 24 oz Drink</td>
  </tr>
  <tr class="color-row">
    <td style="width:175px;">Papa John’s (SUMC &amp; PSU)</td>
    <td>One Slice Pizza, Two Bread Sticks &amp; 24 oz Drink</td>
  </tr>
  <tr>
    <td style="width:175px;">Park Ave. Market (PSU)</td>
    <td>Crispy Chicken Patty Sandwich with Small Fries &amp; 24 oz Drink</td>
  </tr>
</table>