<style>
#left_margin {
	margin-left: 20px;	
}
#left_margin ul li {
	font-size:14px;
	font-weight: normal;
	display:inline;
}

</style>

<div id="logo">
  <img src="template/images/logos/core.gif" alt="Core"/>
</div>
<div id="desc" >
  <p>Core is designed to offer healthy, tasty and unique food options that meet your needs.</p>
</div>
<div>
    <h1>How it works:</h1>
	<div id="left_margin">
    <ul>
    <li>•	Fill your bowl to the rim with our fresh ingredients  </li> <br />
	<li>•	Add a protein </li><br />  
	<li>•	Choose your greens</li> <br />
	<li>•	Need a crunch? We have croutons, seeds and nuts</li><br />  
	<li>•	Choose your dressing</li><br /> 
	<li>•	ENJOY!!!</li> 
    </ul>
	</div>
</div>
