<?php
?>
<style>
.list{
	font-size:9px;
	color:#444444;
	font-weight:bold;
}
</style>
<div>
<h1>Delivery</h1>

<h2>Delivery &amp; Order Information</h2>
<p class="list">&#149; Minimum four sandwiches per delivery.<br>
	&#149; Delivery hours are Monday thru Thursday 7:30a&#150;4p, Friday 7:30a&#150;2:30p, Breakfast 7:30a-11a.<br>
	&#149; Delivery is limited to the main UA campus only.<br>
	&#149; Tax is included.<br>
	&#149; Phone order must be received two hours in advance of delivery time.<br>
	&#149; Questions? Call 621-8625<br>
</p>


<table border="0" cellpadding="0" cellspacing="0" width="90%" bgcolor="#333333">
	<tr>
		<td>
			<table border="0" cellpadding="4" cellspacing="1" frame="" width="100%">
				<tr>
					<td valign="top" bgcolor="#ffffff">
						<div align="right">
							<span style="font-size:32px;font-weight:bold;color:#000000;">1</span>
					  </div>
					</td>
					<td valign="top" bgcolor="#cccccc"><b><a href="/template/resources/forms/Eller_DeliveryForm.pdf" target="_blank">Download The Counter order form!</a></b>
						
					</td>
				</tr>
				<tr>
					<td valign="top" bgcolor="#ffffff">
						<div align="right">
							<span style="font-size:32px;font-weight:bold;color:#000000;">2</span>
						</div>
					</td>
					<td valign="top" bgcolor="#cccccc"><b>Fill out the form</b>.</td>
				</tr>
				<tr>
					<td valign="top" bgcolor="#ffffff">
						<div align="right">
							<span style="font-size:32px;font-weight:bold;color:#000000;">3</span>
					  </div>
					</td>
					<td valign="top" bgcolor="#cccccc"><b>Phone it in</b>.<br>
						621.8625 or bring completed form to The Counter
						<p>Thank-you!</p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</div>