<div id="logo">
  <img src="template/images/logos/froyo.gif" alt="Froyo"/>
</div>
<div id="desc" >
  <p>
  	Located both in Cactus Grill and U-Mart, Fro-Yo serves your choice of frozen yogurt flavor along with a wide variety of yummy goodies to top it off. Enjoy customizing breakfast yogurt and trail mix as well as a fro-yo flurry.
  </p>
</div>
<div id="menu-content" style="clear:both; margin-top:-5px;">
  <style>
  	.line-item{
  		margin-bottom:5px;
  	}
  	p{
  		margin-top:0px;
  	}
  </style>
  <div id="froyo" style="display:block;">
    <h1>Fro-Yo</h1>
    <h2>Breakfast Yogurt</h2>
    <?php 
    	full_line_item('Small', 'includes 2 goodies', '2.69');
    	full_line_item('Large', 'includes 2 goodies', '3.19');
    ?>
    <h2>Fro Yo</h2>
    <?php 
    	full_line_item('Small', 'includes 2 goodies', '2.29');
    	full_line_item('Large', 'includes 2 goodies', '2.79');
    	full_line_item('Fro Yo Flurry', 'jumbo-sized fro yo whipped with 3 goodies', '3.29');
    	full_line_item('goodies', '', '.55');
    ?>
    <p class="list" style="float:left;">
    	golden raisins<br />
    	raisins<br />
    	raspberries<br />
    	blueberries<br />
    	mango<br />
    	strawberries<br />
    	bananas<br />
    	banana chips<br />
    	peaches<br />
    	dried apricots<br />
    	dried papaya<br />
    	dried cranberries
    </p>
    <p class="list" style="float:left; margin-left:10px;">
    	pineapple<br />
    	coconut<br />
    	cinnamon apples<br />
    	chopped peanuts<br />
    	chopped pecans<br />
    	almonds<br />
    	cashews<br />
    	chopped walnuts<br />
    	honey roasted peanuts<br />
    	mixed nuts<br />
    	granola
    </p>
    <p class="list" style="float:left; margin-left:10px;">
    	graham cracker crumbs<br />
    	mini pretzels<br />
    	yogurt pretzels<br />
    	sour neon worms<br />
    	gummi bears<br />
    	rainbow sprinkles<br />
    	chocolate sprinkles<br />
    	chocolate chips<br />
    	oreos<br />
    	m&amp;m's<br />
    	heath bar
    </p>
    <p class="list" style="float:left; margin-left:10px;">
    	reese's peanut butter cups<br />
    	butterfinger<br />
    	reese's pieces<br />
    	snickers<br />
    	brownie bites<br />
    	chocolate syrup<br />
    	butterscotch syrup<br />
    	caramel syrup<br />
    	strawberry syrup
    </p>
    <p class="list" style="clear:both;">*breakfast yogurt &amp; some goodies are not avaialabe at Umart location.</p>      
  </div>
</div>