<?php
?>
<style>
.list{
	font-size:9px;
	color:#444444;
	font-weight:bold;
}
</style>
<div>
<h1>Delivery</h1>
<p class="list">
Got a last minute meeting or working in for lunch?<br />
No problem. The On Deck Deli now delivers sandwiches and salads&#151;and they&#146;re just a fax away!<br />
Simply fax your order to 626-EATS (626-3287), at least two hours in advance of delivery time.<br />
Each sandwich is dressed with tomatoes and lettuce, and comes with your choice of Lay's chips, beverage, and a delicious dessert. Mayonnaise, mustard, and a sliced kosher pickle come on the side.
</p>



<h2>Delivery &amp; Order Information</h2>
<p class="list">&#149; Minimum four sandwiches per delivery.<br>
	&#149; Delivery hours are Monday thru Friday 10a&#150;5p.<br>
	&#149; Delivery is limited to the main UA campus only.<br>
	&#149; Tax is included.<br>
	&#149; Fax order must be received two hours in advance of delivery time.<br>
	&#149; Questions? Call 621-7041<br>
</p>


<table border="0" cellpadding="0" cellspacing="0" width="90%" bgcolor="#333333">
	<tr>
		<td>
			<table border="0" cellpadding="4" cellspacing="1" frame="" width="100%">
				<tr>
					<td valign="top" bgcolor="#ffffff">
						<div align="right">
							<span style="font-size:32px;font-weight:bold;color:#000000;">1</span>
						</div>
					</td>
					<td valign="top" bgcolor="#cccccc"><b><a href="/template/resources/forms/ondeck_DeliveryForm.pdf" target="_blank">Download the On Deck Delivers form!</a></b>
						
					</td>
				</tr>
				<tr>
					<td valign="top" bgcolor="#ffffff">
						<div align="right">
						<span style="font-size:32px;font-weight:bold;color:#000000;">2</span>
						</div>
					</td>
					<td valign="top" bgcolor="#cccccc"><b>Fill out the form</b>.</td>
				</tr>
				<tr>
					<td valign="top" bgcolor="#ffffff">
						<div align="right">
						<span style="font-size:32px;font-weight:bold;color:#000000;">3</span>
						</div>
					</td>
					<td valign="top" bgcolor="#cccccc"><b>Fax it in</b>.<br>
						<b>626.EATS</b> (626.3287)
						<p>Thank-you!</p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</div>