<?php

/* variables that set the characteristics of how
   the current section should be displayed */
   



$area = 'csil';
$template = 'standard';


/* the main page for this section */
$section_title 		= 'CSIL';
$section_title_img	= 'none';
$section_url 		= '/csil/index.php';


$photo_url		= '/csil/Accolades/AccoladesSI.gif';
$photo_alt		= 'leadership programs';	


/* links to show for the parents */
/* lower indexes are more ancestral */
$parent_title	= array('involvement');
$parent_url		= array('/csil/index.php');


/* links for the section's children */

$child_title = 	array('Accolades',
					  'Dean of Students Emerging Leader Award',
					  'Outstanding Graduate Student Leader Award',
					  'Outstanding Faculty Award',
					  'Outstanding Professional Staff Member Award',
					  'Outstanding Social Justice Advocate Award',
					  'Outstanding Senior Leader Award',
					  'Outstanding Teaching Assistant/Graduate Assistant of the Year Award',
					  'President’s Award for Servant Leadership',
					  'Outstanding Student Organization Advisor Award', 
					  'Outstanding Collaborative Program Award',
					  'Department of the Year Award',
					  'Outstanding Multi-Cultural Program Award',
					  'Outstanding Community Service Award',
					  'Outstanding New Student Organization Award',
					  'Outstanding Philanthropy Award',
					  'Student Affairs Outstanding Organization Award',
					 );
					 
					 
$child_url = 	array('/csil/accolades/index.php',
					  '/csil/accolades/indvawards/Emerglead.php?indvq=9',
					  '/csil/accolades/indvawards/GSLA.php?indvq=7',
					  '/csil/accolades/indvawards/OFA.php?indvq=2',
					  '/csil/accolades/indvawards/OPA.php?indvq=1',
					  '/csil/accolades/indvawards/OSJL.php?indvq=8',
					  '/csil/accolades/indvawards/OSLA.php?indvq=6',
					  '/csil/accolades/indvawards/OTA.php?indvq=3',
					  '/csil/accolades/indvawards/PASL.php?indvq=5',
					  '/csil/accolades/indvawards/SAA.php?indvq=4',
					  '/csil/accolades/groupawards/CollabProg.php?groupq=6',
					  '/csil/accolades/groupawards/Dept.php?groupq=1',
					  '/csil/accolades/groupawards/OMCPA.php?groupq=7',
					  '/csil/accolades/groupawards/OSCS.php?groupq=4',
					  '/csil/accolades/groupawards/OSNSA.php?groupq=2',
					  '/csil/accolades/groupawards/phila.php?groupq=5',
					  '/csil/accolades/groupawards/StuAffOrg.php?groupq=3',
					 );


//$sidebar_content = <<<EOD
//EOD;


?>