<div id="nav_bar">
	    
	    	<div id="<?=$page=='Home'?'selected_nav_item':''?>" class="nav_item"><a class="divlink" href="index.php">home</a>        
	        </div>
	    
	    	<div class="nav_item"><a class="divlink" href="reg.php">register</a>        	
				
	        </div>
	        
	        
	    	<div id="<?=$page=='At a Glance'?'selected_nav_item':''?>" class="nav_item"><a class="divlink" href="glance.php">at a glance</a>        	
	        </div>
	        
	        
	         <div id="<?=$page=='Friday\'s Events'?'selected_nav_item':''?>" class="nav_item"><a class="divlink" href="viewevents.php?day=fri">friday's events</a>        	
	        </div>
	
	
	    	<div id="<?=$page=='Saturday\'s Events'?'selected_nav_item':''?>" class="nav_item"><a class="divlink" href="viewevents.php?day=sat">saturday's events</a>        	
	        </div>
	
	    	<div id="<?=$page=='Sunday\'s Events'?'selected_nav_item':''?>" class="nav_item"><a class="divlink" href="viewevents.php?day=sun">sunday's event</a>     	
	        </div>
	        
	        
	         <div id="<?=$page=='Directions'?'selected_nav_item':''?>" class="nav_item"><a class="divlink" href="directions.php">directions</a>        	
	        </div>
	
	
			<div id="<?=$page=='Contributors'?'selected_nav_item':''?>" class="nav_item" style="border-right:none;"><a class="divlink" href="recognition.php">contributors</a>        	
	        </div>
	        
	        <div id="clearer"> <!--Use this to make all the floated nav divs live inside the outer div -->
	        	&nbsp;
	        </div>
</div>