<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td colspan="3" valign="top"><h2>Student Union Features:</h2>
			<br>
		</td>
	</tr>
	<tr>
		<td valign="top" width="50%">
			<p>
				<a href="/dining/sumc/arizonaroom">Arizona Room</a>
				<br/>all-you-can-eat style of dining with table service in a refined setting.
			</p>
  			
			<p>
				<a href="/dining/sumc/cactus">Cactus Grill</a>
				<br>homemade breakfasts, lunch and dinners, salad bar, BBQ and much more.
			</p>
      		
			<p>
				<a href="/dining/sumc/chickfila">Chik-fil-A</a>
				<br/>chicken sandwiches, waffle fries and house-made lemonade
			</p>
            <p>
				<a href="/dining/sumc/core">Core</a>
				<br>create your own salads with all fresh ingredients.
			</p>
			<p>
				<a href="/dining/sumc/einsteins">Einstein Bros Bagels</a>
				<br>famous bagels, spreads and coffee to start your day.
			</p>
			<p>
				<a href="/dining/sumc/iq">IQ Fresh</a>
				<br>healthy smoothies, wraps, salads and breakfast.
			</p>
			<p>
				<a href="/dining/sumc/nrich">Nrich Urban Market </a>
				<br>Nutrient Rich & Delicious pressed juice, seasonal produce, ground nut butter, and more.
			</p>
		</td>
		<td width="15">&nbsp;&nbsp;&nbsp;&nbsp;</td>
		<td valign="top" width="50%">
			<p>
				<a href="/dining/sumc/ondeck">On Deck Deli</a>
				<br>gourmet sandwiches<br><i><a href="/dining/sumc/ondeck">delivery now available!</a></i>
			</p>
			<p>
				<a href="/dining/sumc/panda">Panda Express</a>
				<br>authentic Chinese food
			</p>
			<p>
				<a href="/dining/sumc/pangea">Pangea</a>
				<br>World Cuisine, Sushi, Italian & Gluten Free Headquarters
			</p>
			<p>
				<a href="/dining/sumc/papajohns">Papa John's Pizza</a>
				<br>pizza and salads
			</p>

			<p>
				<a href="/dining/sumc/sabor">Sabor</a>
				<br>modern Mexican fare
			</p>
			<p>
				<a href="http://www.starbucks.com">Starbucks</a>
				<br>Located in the <a href="http://www.uabookstores.arizona.edu" target="self">UA BookStores</a>
			</p>
			<p>
				<a href="/dining/sumc/umart">U-Mart</a>
				<br>groceries, snacks, grab-n-go, fro-yo and so much more
			</p>
		</td>
	</tr>
	<tr>
		<td colspan="3"><br>
			<h2>Global Center Features:</h2>
			<br>
		</td>
	</tr>
	<tr>
		<td valign="top" width="50%">
      		<p>
				<a href="/dining/psu/parkdining">Park Avenue Dining</a>
				<br>Cereal bar, corner Cafe, Hotline Entrees, IQ smoothies, On Deck Deli, Route 66 Grill, Salad Bar, Wrap It!
			</p>
		  	<p>
				<a href="/dining/psu/parkmarket">Park Avenue Market</a>
				<br>groceries, snacks, frozen and fresh foods, and dorm room essentials
			</p>
		  	<p>
				<a href="/dining/psu/bageltalk">Bagel Talk</a>
				<br>large selection of bagels, fresh-made sandwiches and premium coffee.
			</p>
         </td>
		 <td width="15">&nbsp;&nbsp;&nbsp;&nbsp;</td>
		 <td valign="top" width="50%">
			<p>
				<a href="/dining/psu/core/">Core+</a> (all gluten free)<br>
				custom built omeletes, salads, stir fry and quesadillas
			</p>
      		<p>
				<a href="/dining/psu/lapetite">La Petite Patisserie</a>
				<br>sweet and savory crepes, fruit smoothies, and coffee and espresso.
			</p>
		</td>
	</tr>
	<tr>
		<td colspan="3"><br>
			<h2>More Dining Around Campus:</h2><br>
			<p>For students on the go, get quick meals, grill items, drinks, specialty coffees, and snacks at the Union Food Stops, conveniently located around campus.<br></p>
			<br>
		</td>
	</tr>
	<tr>
		<td valign="top" width="50%">
			<p><b><a href="/dining/other/fuel">Shake Smart @ the Rec</a></b><br>
			freshly blended protein shakes, organic acai bowls, organic peanut butter and banana sandwiches, oatmeal, coldbrew coffee, whole wheat wraps, and kombucha on tap</p>

			<p><b><a href="/dining/other/highland">Highland Market</a></b> (in Villa del Puente)<br>
			breakfast burritos, groceries, deli, salad, coffee bar, hot plates & grill<br>

			<p><b><a href="/dining/other/beardownkitchen" >Bear Down Kitchen</a></b> (in North End Zone)<br>
			Training Table, endless breakfast, lunch & made to order plates<br>

			<p><b><a href="/dining/other/starbuckslib" >Starbucks @ Library</a></b><br>
			Signature coffee & grab 'n go sandwiches<br>

		</td>
		<td width="15">&nbsp;</td>
		<td valign="top" width="50%">
			
			<b>Convenience Stores<br></b>
			<p>
				McClelland Hall <br />
				McKale Center <br />
				Nucleus <span class="small">@ Bio5</span>
			</p>

			<p>
				<b>Vending Machines<br></b>
				use your Meal Plan, credit card, or cash in over 350 vending machines on campus, each loaded with your favorite sancks, sodas, & drinks
			</p>

			<b>Hot Dog Food Stops<br></b>
			<p>
				Harvill bldg<br />
				Nugent bldg
			</p>

			<p>
				<b>Coffee Carts<br></b>
				Modern Languages bldg
				Social Sciences bldg
			</p>

		</td>
	</tr>
</table>
