<style type="text/css" >
	.center-list li {
		margin-top: 1.5em !important;
	}	
	.center-list a:active, .center-list a:link, .center-list a:visited {
		color: #444444 !important;
		font-weight: bold !important;
	}
	.center-list a:hover {
		color: #CC0033 !important;
		font-weight: bold !important;
	}
	.center-list li ul li {
		margin-top: 2px !important;
	}

#link_title a:active, #link_title a:link,  #link_title a:visited {
	font-size:16px;
	font-weight: bold;
	color: #2B38D1;
	text-decoration:underline;
	display:inline;
}
#link_title a:hover{
	font-size:16px;
	font-weight: bold;
	color: #F58523;
	text-decoration:underline;
	display:inline;
}
</style>

<div style="margin-top:-80px; font-size:16px;">
<h1>Rooftop Garden Competition Winners</h1>
<p style="font-size: 14px;line-height:150%">
<strong>1st Place Winners - Team 3</strong><br />
Daniel Gillespie, Brian Caplan, 
Raul Moraga, 
Robert Melvin, 
Nicholas Tritz
<br /><br />
<strong>2nd Place Winners - Team 13</strong><br />
Erin Scott,  
Meck Slagle,  
Amy Stalkfleet,  
Rebecca Van Rhee,  
Ryan Yamauchi 
<br /><br />
<strong>3rd Place Winners - Team 7</strong><br />
Catalina Fernandez-Moores,  
Victoria Karlsson,  
Sarah Land,  
Sean McBride 
<br /><br />
<strong>Participating Teams:</strong><br />
<strong>Team 2</strong><br />
NaRayah Runyon,  
Maria Marzano,  
Luis Garcia,  
Chetan Bafna,  
Cody Sheldon 
<br /><br />
<strong>Team 8</strong><br />
Joseph Lewandowski,  
Maximilian Lim,  
Sarah Patterson 
<br /><br />
<strong>Team 18</strong><br />
Hunter Brown,  
Seth Buell,  
Fernanda Fraijo Arce,  
Francisco Gomez,  
Erik Petersen 
<br /><br />

For any questions regarding the Rooftop Garden Case Competition please email Christina Partica at <a href="mailto:cpartica@email.arizona.edu" />cpartica@email.arizona.edu</a>.
</p>
</div>
<p>&nbsp;</p><p>&nbsp;</p>
<p>
<img src="/template/images/banners/Rooftop_Garden_bottom.jpg" />
</p>